# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626bdd6496aa11e254ea0634e85064b1934ddc8efe50d7576670a25657081aa5dd4f7f53d50ed523ffa9876ec282d559e469a43993365bf5e0b7df82a3cbbbd4

test:
  secret_key_base: 44fd4aad27e26b922f9b841521d4044cfe41440d3ece9f0d91e4864ccc08241a2a103e5d285d1adf419fc285aa74ba341ed14a725f28e2575e6e3eba7a69f9b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
